travis:
  secure:
    BINSTAR_TOKEN: O/g681V40xxwbs1RaDeQXIpO71E8xwkSHudD4hgg7FxR03A+5cHGH75a3FxlNos6dQivt+IF3QvsBFSW+9VrHX7lSCngxqwVrpP0/8AIc4AZOSuKrZxULKr4pg1P/OisRnl3t3ogwaMuSgiq46XDy4B271nwpbbiS0WxnKxIXBQu5f84VhMh86ElyptpUJrnnOVU80X9Y5JX/gxNPkRJtmJtQnyjRAjALheFBwgXMCr43c3V3pDqSPWryL74p7EB8R6Krs7VS3dUpzAVSSG5UVWhIW0VNKR10E8A9jFHBKz98Aifchu31vioZckwW1SIOXWizVqz+kcv5X7dXMt3o0whaUqQ79JoDFdo2Dw2CGTRshfLQ7qY7MMm5cd3NziFQ2f8Dqjoy6TmwDWPI743MUxJLFV2vEcwPtlxaoeqD73u0IGfEPtutJh63OyjnxaFPzdGM/hPVyKlHCVHHkOW0Uw67p02THeeCS6w9b5ce68ZFK0fh24AkTbE51Rf6lplFjZk2tNcjsKV6fHJFzG90kv0LRCQXXnszoCeRH2nM2ffBYOIph3ESuFYQ0FROavqaMwQ7tYr8BURoKAsuT/e4mh8KcbpjWskcjA48cfJ5YFOjGLUqtWtSN2qaRSDAaxlbJ9PJsSytRHqv2f7ADDLVU9OxApSwiW/S0nnvwV9oR4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
